resources:
  repositories:
  # shared library repository
  - repository: arcade
    type: github
    endpoint: sbomer
    name: dotnet/arcade
    ref: refs/heads/master

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true


phases:

###
###  Windows: x64, x86, arm64, arm
###

- template: /eng/common/templates/phases/base.yml@arcade
  parameters:
    queue:
      name: dotnet-external-temp
      timeoutInMinutes: 180
      parallel: 4
      matrix:
        x64 release innerLoop:
          buildConfig: release
          buildConfigUpper: Release
          archType: x64
        x86 release innerLoop:
          buildConfig: release
          buildConfigUpper: Release
          archType: x86
        arm release innerLoop:
          buildConfig: release
          buildConfigUpper: Release
          archType: arm
        arm64 release innerLoop:
          buildConfig: release
          buildConfigUpper: Release
          archType: arm64
    agentOs: Windows_NT
    name: Windows_NT
    steps:
#    - task: DotNetCoreInstaller@0
#      inputs:
#        version: 2.1.400
    # necessary to install python!
    - script: eng\common\init-tools-native.cmd -InstallDirectory $(Build.SourcesDirectory)\native-tools -Force
      displayName: Install native tools
      # TODO: do we want to skiptests? skipbuildpackages? IBCOptimize? EnforcePGO? pass an OfficialBuildId? SkipRestore? signtype? file logging parameters?
    - script: .\init-tools.cmd
      displayName: Init tools
    - script: .\Tools\dotnetcli\dotnet.exe msbuild build.proj /p:RestoreDuringBuild=true /t:Sync
      displayName: Sync
    # skiprestore sets restoreduringbuild to false. that step has been separated out.
    - script: set __TestIntermediateDir=int&&build.cmd $(buildConfig) $(archType) -skiptests -skipbuildpackages -skiprestore -priority=0
      displayName: Build
    - script: echo Sign!
      displayName: Sign Binaries (empty for now)
    - script: echo Publish!
      displayName: Publish build to some location (empty for now)
#    - script: build-test.cmd $(buildConfig) $(archType) buildagainstpackages runtimeid win-$(archType) -Priority=0
#      displayName: Build tests
    - script: build-test.cmd $(buildConfig) $(archType) -Priority=0
      displayName: Build tests
    - script: .\Tools\dotnetcli\dotnet.exe msbuild tests\helixprepnew.proj /p:CORE_ROOT=$(Build.SourcesDirectory)\bin\tests\Windows_NT.$(archType).$(buildConfigUpper)\tests\core_root /p:__BuildType=$(buildConfig) /p:__BuildArch=$(archType)
      displayName: Prepare test directories for helix
    - task: DotNetCoreCLI@2
      inputs:
        command: custom
        projects: tests\helixpublishwitharcade.proj
        custom: msbuild
        arguments: '/t:test'
      displayName: Send tests job to Helix
      env:
        HelixAccessToken: $(HelixTestAccessToken)




###
### Linux x64
###

- template: /eng/common/templates/phases/base.yml@arcade
  parameters:
    queue:
      name: Hosted Ubuntu 1604
      timeoutInMinutes: 180
      parallel: 3
      matrix:
        x64 release innerloop:
          buildConfig: release
          buildConfigUpper: Release
          archType: x64
          buildOS: Linux
    agentOs: Ubuntu
    name: Ubuntu
    steps:
    - script: sudo apt install cmake llvm-3.9 clang-3.9 lldb-3.9 liblldb-3.9-dev libunwind8 libunwind8-dev gettext libicu-dev liblttng-ust-dev libcurl4-openssl-dev libssl-dev libkrb5-dev libnuma-dev
      displayName: Install native dependencies
#    - task: DotNetCoreInstaller@0
#      inputs:
#        version: 2.1.400
#    - script: bash ./eng/common/init-tools-native.sh --installdirectory $(Agent.BuildDirectory)/native-tools -Force
#      displayName: Install native tools
    - script: ./init-tools.sh
      displayName: Init tools
    - script: ./Tools/dotnetcli/dotnet msbuild build.proj /p:RestoreDuringBuild=true /t:Sync
      displayName: Sync
    - script: ./build.sh $(buildConfig) $(archType) -skipnuget -skiprestore
      displayName: Build
    - script: echo Sign!
      displayName: Sign Binaries (empty for now)
    - script: echo Publish!
      displayName: Publish build to some location (empty for now)
    - script: ./build-test.sh $(buildConfig) $(archType)
      displayName: Build tests
    - script: ./Tools/dotnetcli/dotnet msbuild tests/helixprepnew.proj /p:CORE_ROOT=$(Build.SourcesDirectory)/bin/tests/$(buildOS).$(archType).$(buildConfigUpper)/Tests/Core_Root /p:__BuildType=$(buildConfig) /p:__BuildArch=$(archType)
      displayName: Prepare test directories for helix
    - task: DotNetCoreCLI@2
      inputs:
        command: custom
        projects: tests/helixpublishwitharcade.proj
        custom: msbuild
        arguments: '/t:test'
      displayName: Send tests job to Helix
      env:
        HelixAccessToken: $(HelixTestAccessToken)


###
### RedHat x64
###




###
### macOS x64
###

- template: /eng/common/templates/phases/base.yml@arcade
  parameters:
    queue:
      name: Hosted macOS
      timeoutInMinutes: 180
      parallel: 3
      matrix:
        x64 release innerloop:
          buildConfig: release
          buildConfigUpper: Release
          archType: x64
          buildOS: OSX
    agentOs: MacOS
    name: MacOS
    steps:
#    - script: brew install cmake # mac machine already has cmake 3.12.2. this command fails, saying:
  #  Error: cmake 3.12.2 is already installed
  #  To upgrade to 3.12.3, run `brew upgrade cmake`
    # - script: brew list icu4c # this fails when it's not installed.
    - script: brew install icu4c
    - script: brew link --force icu4c
    # - script: brew list openssl
    - script: brew install openssl
#     - task: DotNetCoreInstaller@0
#       inputs:
#         version: 2.1.400
#    - script: eng/common/init-tools-native.sh --installdirectory $(Agent.BuildDirectory)/native-tools -Force
#      displayName: Install native tools
#    - script: bash ./eng/common/init-tools-native.sh --installdirectory $(Agent.BuildDirectory)/native-tools -Force
#      displayName: Install native tools
    - script: ./init-tools.sh
      displayName: Init tools
    - script: ./Tools/dotnetcli/dotnet msbuild build.proj /p:RestoreDuringBuild=true /t:Sync
      displayName: Sync
    - script: ./build.sh $(buildConfig) $(archType)
      displayName: Build
    - script: echo Sign!
      displayName: Sign Binaries (empty for now)
    - script: echo Publish!
      displayName: Publish build to some location (empty for now)
    - script: ./build-test.sh $(buildConfig) $(archType)
      displayName: Build tests
    - script: ./Tools/dotnetcli/dotnet msbuild tests/helixprepnew.proj /p:CORE_ROOT=$(Build.SourcesDirectory)/bin/tests/$(buildOS).$(archType).$(buildConfigUpper)/Tests/Core_Root /p:__BuildType=$(buildConfig) /p:__BuildArch=$(archType)
      displayName: Prepare test directories for helix
    - task: DotNetCoreCLI@2
      inputs:
        command: custom
        projects: tests/helixpublishwitharcade.proj
        custom: msbuild
        arguments: '/t:test'
      displayName: Send tests job to Helix
      env:
        HelixAccessToken: $(HelixTestAccessToken)

#
#- phase: Windows_NT_x64 Formatting
#    queue:
#      name: Hosted VS2017
#      steps:
#        - script: 'python -u tests\\scripts\\format.py -c %Agent.WorkingDirectory% -o Windows_NT -a x64'
#
#- template: /eng/ryujit-perf.yml
#  parameters:
#    agentOs: Windows_NT
#    queue:
#      name: Hosted VS2017
#      parallel: 4
#      matrix:
#        x64_release_full_opt_ryujit_perf:
#          scenario: full_opt
#          buildConfig: release
#          archType: x64
#        x64_release_min_opt_ryujit_perf:
#          scenario: min_opt
#          buildconfig: release
#          archType: x64
#        x86_release_full_opt_ryujit_perf:
#          scenario: full_opt
#          buildconfig: release
#          archType: x86
#        x86_release_min_opt_ryujit_perf:
#          scenario: min_opt
#          buildConfig: release
#          archType: x86


#  CentOS7.1 x64 Checked Innerloop Build and Test
#  CentOS7.1 x64 Debug Innerloop Build
#  Linux-musl x64 Debug Build
#  OSX 10.12 x64 Checked InnerLoop Build and Test
#  Tizen armel Corss Checked Innerloop Build and Test
#  Ubuntu arm Cross Checked InnerLoop Build and Test
#  Ubuntu arm64 Cross Debug Innerloop Build
#  Ubuntu x64 Checked Innerloop Build and Test
#  Ubuntu x64 Formatting
#  Windows_NT arm Cross Checked Innerloop Build and Test
#  Windows_NT arm64 Cross Checked Innerloop Build and Test
#  Windows_NT x64 Checked CoreFx tests
#  Windows_NT x64 Release CoreFx tests

#- template: /eng/common/templates/phases/base.yml@arcade
#  parameters:
#    queue:
#      name: Hosted Ubuntu 1604
#      timeoutInMinutes: 180
#      parallel: 1
#    agentOs: Ubuntu
#    name: UbuntuHelix
#    steps:
#      - task: DotNetCoreCLI@2
#        inputs:
#          command: custom
#          projects: helixtest.proj
#          custom: msbuild
#          arguments: '/t:test'
#        displayName: Send test workload to helix
#        env:
#          HelixAccessToken: $(HelixTestAccessToken)
#
#- template: /eng/common/templates/phases/base.yml@arcade
#  parameters:
#    queue:
#      name: dotnet-external-temp
#      timeoutInMinutes: 180
#      parallel: 1
#    agentOs: Windows_NT
#    name: WindowsHelix
#    steps:
#      - task: DotNetCoreCLI@2
#        inputs:
#          command: custom
#          projects: helixtest.proj
#          custom: msbuild
#          arguments: '/t:test'
#        displayName: Send test workload to helix
#        env:
#          HelixAccessToken: $(HelixTestAccessToken)
