resources:
  repositories:
  # shared library repository
  - repository: arcade
    type: github
    endpoint: sbomer
    name: sbomer/arcade
    ref: refs/heads/arcadeChanges

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true


phases:

##   The following is the matrix of test runs that we have. This is
##   duplicated for each os/arch combination in platform-matrix.yml.g

##
##   Product build       Test build              Test run
##   (Azure DevOps)      (Azure DevOps)          (helix)
##
##   ###########################################################################################
##
##   Debug
##
##   Checked ----------> Pri0 -----------------> plain runtests
##           |
##           \---------> Pri1 -----------------> plain runtests
##           |                \----------------> jitstress
##           |                \----------------> gcstress
##           |                \----------------> maybe more (dynamically selected runtest modes)
##           |
##           \---------> Pri1 crossgen --------> plain runtests
##                                     \-------> jitstress
##                                     \-------> gcstress
##                                     \-------> maybe more (dynamically selected runtest modes)
##
##   Release ----------> Pri1 -----------------> plain runtests
##           |
##           \---------> Pri1 crossgen --------> plain runtests
##
##

### Each build or test job is defined in Azure DevOps, and will show
### up in the UI in the order in which they are defined here. The
### build and test build job matrix is defined statically, but
### queue-time inputs can be used to control whether a job executes
### (used to select which jobs run in ci vs for official builds), or
### to select test modes. This should eventually be used to enable
### requesting specific test runs from pull requests.


# Debug build
- template: platform-matrix.yml
  parameters:
    jobTemplate: build-pipeline.yml
    buildConfig: debug

# Checked build
- template: platform-matrix.yml
  parameters:
    jobTemplate: build-pipeline.yml
    buildConfig: checked

# Release build
- template: platform-matrix.yml
  parameters:
    jobTemplate: build-pipeline.yml
    buildConfig: release


# Checked Pri0 test build
- template: platform-matrix.yml
  parameters:
    jobTemplate: test-pipeline.yml
    buildConfig: checked
    jobParameters:
      testBuild: priority0


# Checked Pri1 test build
- template: platform-matrix.yml
  parameters:
    jobTemplate: test-pipeline.yml
    buildConfig: checked
    jobParameters:
      testBuild: priority1

# TODO: Checked Pri1 crossgen test build

# Release Pri1 test build
- template: platform-matrix.yml
  parameters:
    jobTemplate: test-pipeline.yml
    buildConfig: release
    jobParameters:
      testBuild: priority1

# TODO: Release Pri1 crossgen test build


# Publish build information to Build Assets Registry

# This job gathers build assets from the pipeline (from each official
# product build job), and publishes them to the build assets
# registry. Its dependencies should be updated to include all of the
# official builds if we add more platform/arch combinations.

# TODO: Enable publish to BAR
#- ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
#  - template: /eng/common/templates/phases/publish-build-assets.yml@arcade
#- phase: publish_bar
#  displayName: publish to BAR (empty currently)
#  queue:
#    name: Hosted VS2017
#  dependsOn:
#  - build_Linux_x64_release
#  - build_OSX_x64_release
#  - build_Windows_NT_x64_release
#  - build_Windows_NT_x86_release
#  - build_Windows_NT_arm_release
#  - build_Windows_NT_arm64_release
  # TODO: enable these builds
  #  - build_rhel_x64_release
  #  - build_alpine_x64_release
  #  - build_crossbuild_arm_release
  #  - build_crossbuild_arm64_release

# TODO
#- phase: Windows_NT_x64 Formatting
#    queue:
#      name: Hosted VS2017
#      steps:
#        - script: 'python -u tests\\scripts\\format.py -c %Agent.WorkingDirectory% -o Windows_NT -a x64'
#
#- template: /eng/ryujit-perf.yml
#  parameters:
#    agentOs: Windows_NT
#    queue:
#      name: Hosted VS2017
#      parallel: 4
#      matrix:
#        x64_release_full_opt_ryujit_perf:
#          scenario: full_opt
#          buildConfig: release
#          archType: x64
#        x64_release_min_opt_ryujit_perf:
#          scenario: min_opt
#          buildconfig: release
#          archType: x64
#        x86_release_full_opt_ryujit_perf:
#          scenario: full_opt
#          buildconfig: release
#          archType: x86
#        x86_release_min_opt_ryujit_perf:
#          scenario: min_opt
#          buildConfig: release
#          archType: x86


#  CentOS7.1 x64 Checked Innerloop Build and Test
#  CentOS7.1 x64 Debug Innerloop Build
#  Linux-musl x64 Debug Build
#  OSX 10.12 x64 Checked InnerLoop Build and Test
#  Tizen armel Cross Checked Innerloop Build and Test
#  Ubuntu arm Cross Checked InnerLoop Build and Test
#  Ubuntu arm64 Cross Debug Innerloop Build
#  Ubuntu x64 Checked Innerloop Build and Test
#  Ubuntu x64 Formatting
#  Windows_NT arm Cross Checked Innerloop Build and Test
#  Windows_NT arm64 Cross Checked Innerloop Build and Test
#  Windows_NT x64 Checked CoreFx tests
#  Windows_NT x64 Release CoreFx tests
