parameters:
  testlegs: ''

jobs:
- ${{ if contains('innerloop', parameters.testlegs) }}:
  - job: innerloop
    steps:
      - script: echo innerloop!
- ${{ if contains('outerloop', parameters.testlegs) }}:
  - job: outerloop
    steps:
      - script: echo outerloop!
- ${{ if contains('gcstress', parameters.testlegs) }}:
  - job: gcstress
    steps:
      - script: echo gcstress!
