parameters:
  testlegs: {}

jobs:
- ${{ if in('innerloop', testlegs) }}:
  - job:
    steps:
      - script: echo innerloop!
- ${{ if in('outerloop', testlegs) }}:
  - job:
    steps:
      - script: echo outerloop!
- ${{ if in('gcstress', testlegs) }}:
  - job:
    steps:
      - script: echo gcstress!
