parameters:
  testlegs: ''

jobs:
- ${{ if in('innerloop', parameters.testlegs) }}:
  - job:
    steps:
      - script: echo innerloop!
- ${{ if in('outerloop', parameters.testlegs) }}:
  - job:
    steps:
      - script: echo outerloop!
- ${{ if in('gcstress', parameters.testlegs) }}:
  - job:
    steps:
      - script: echo gcstress!
