parameters:
  testlegsparam: ''

jobs:
- ${{ if contains(parameters.testlegsparam, 'innerloop') }}:
  - job: innerloop
    steps:
      - script: echo innerloop!
- ${{ if contains(parameters.testlegsparam, 'outerloop') }}:
  - job: outerloop
    steps:
      - script: echo outerloop!
- ${{ if contains(parameters.testlegsparam, 'gcstress') }}:
  - job: gcstress
    steps:
      - script: echo gcstress!
- job: matrixjob_withvars
  variables:
    testlegsinnervar: ${{ parameters.testlegsparam }}
  steps:
    # this works with a distinct variable name
  - script: echo $(testlegsinnervar) variable?
- job: matrixjob_withparams
  steps:
    # this works as long as the entire string is a template expression evaluation
  - script: ${{ format('echo testlegsparam {0}', parameters.testlegsparam) }}
