parameters:
  testlegs: ''

variables:
  testlegs: ${{ parameters.testlegs }}

jobs:
- ${{ if contains(parameters.testlegs, 'innerloop') }}:
  - job: innerloop
    steps:
      - script: echo innerloop!
- ${{ if contains(parameters.testlegs, 'outerloop') }}:
  - job: outerloop
    steps:
      - script: echo outerloop!
- ${{ if contains(parameters.testlegs, 'gcstress') }}:
  - job: gcstress
    steps:
      - script: echo gcstress!
- job: matrixjob_alwayson
  steps:
  - script: echo $(testlegs) variable?
