parameters:
  buildConfig: ''
  buildConfigUpper: ''
  archType: ''

jobs:


### Product build
- template: /eng/common/templates/phases/base.yml@arcade
  parameters:
    name: ${{ format('win_{0}_{1}_build', parameters.archType, parameters.buildConfig) }}
    displayName: ${{ format('Windows_NT {0} {1} Build', parameters.archType, parameters.buildConfigUpper) }}
    queue:
      name: dotnet-external-temp
      timeoutInMinutes: 180
    agentOs: Windows_NT
    variables:
      buildConfig: ${{ parameters.buildConfig }}
      buildConfigUpper: ${{ parameters.buildConfigUpper }}
      archType: ${{ parameters.archType }}
    steps:
#    - task: DotNetCoreInstaller@0
#      inputs:
#        version: 2.1.400
    # necessary to install python!
    - script: eng\common\init-tools-native.cmd -InstallDirectory $(Build.SourcesDirectory)\native-tools -Force
      displayName: Install native tools
      # TODO: do we want to skiptests? skipbuildpackages? IBCOptimize? EnforcePGO? pass an OfficialBuildId? SkipRestore? signtype? file logging parameters?
    - script: .\init-tools.cmd
      displayName: Init tools
    - script: .\Tools\dotnetcli\dotnet.exe msbuild build.proj /p:RestoreDuringBuild=true /t:Sync
      displayName: Sync
    # skiprestore sets restoreduringbuild to false. that step has been separated out.
    - script: set __TestIntermediateDir=int&&build.cmd $(buildConfig) $(archType) -skiptests -skipbuildpackages -skiprestore -priority=0
      displayName: Build

    # Upload build as pipeline artifact
    - task: PublishPipelineArtifact@0
      inputs:
        targetPath: $(Build.SourcesDirectory)\bin\tests\Windows_NT.$(archType).$(buildConfigUpper)

    # Sign
    - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
      - script: echo Sign!
        displayName: Sign Binaries (empty for now)

    ## For official build, publish packages to blob feed
    # First, get secrets from azure key vault
    - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
      - task: AzureKeyVault@1
        inputs:
          azureSubscription: 'DotNet-Engineering-Services_KeyVault'
          KeyVaultName: EngKeyVault
          SecretsFilter: 'dotnetfeed-storage-access-key-1,microsoft-symbol-server-pat,symweb-symbol-server-pat'

    # Next, publish to blob feed
    # TODO: also enable publishing symbols to msdl, symweb
#    - script: eng\common\cibuild.cmd /p:DotNetPublishToBlobFeed=true /p:DotNetPublishBlobFeedKey=$(dotnetfeed-storage-access-key-1) /p:DotNetPublishBlobFeedUrl=https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json
    #- script: .\Tools\dotnetcli\dotnet.exe msbuild 
    #  displayName: Publish build to some location (empty for now)



### Test build and run
- template: /eng/common/templates/phases/base.yml@arcade
  parameters:
    name: ${{ format('win_{0}_{1}_test', parameters.archType, parameters.buildConfig) }}
    displayName: ${{ format('Windows_NT {0} {1} Test Build and Run', parameters.archType, parameters.buildConfigUpper) }}
    queue:
      name: dotnet-external-temp
      timeoutInMinutes: 180
    agentOs: Windows_NT
    variables:
      buildConfig: ${{ parameters.buildConfig }}
      buildConfigUpper: ${{ parameters.buildConfigUpper }}
      archType: ${{ parameters.archType }}
    steps:
    - script: build-test.cmd $(buildConfig) $(archType) -Priority=0
      displayName: Build Pri-0 tests
#    - script: build-test.cmd $(buildConfig) $(archType) buildagainstpackages runtimeid win-$(archType) -Priority=0
#      displayName: Build tests
    - script: .\Tools\dotnetcli\dotnet.exe msbuild tests\helixprep.proj /p:CORE_ROOT=$(Build.SourcesDirectory)\bin\tests\Windows_NT.$(archType).$(buildConfigUpper)\tests\core_root /p:__BuildType=$(buildConfig) /p:__BuildArch=$(archType)
      displayName: Prepare test directories for helix
    - task: DotNetCoreCLI@2
      inputs:
        command: custom
        projects: tests\helixpublishwitharcade.proj
        custom: msbuild
        arguments: '/t:test'
      displayName: Send tests job to Helix
      env:
        HelixAccessToken: $(HelixTestAccessToken)
